# This file was generated by GoReleaser. DO NOT EDIT.
cask "isopolicy" do
  desc "Isovalent Network Policy Recommendations"
  homepage "https://isovalent.com/pollux-blah-blah.com"
  version "v0.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pollux", target: "isopolicy"

  on_macos do
    on_intel do
      url "https://github.com/isovalent/homebrew-isopolicy/raw/refs/heads/main/downloads/v0.16.0/pollux_Darwin_amd64.tar.gz"
      sha256 "45be83f82fbff0c76a59491e5ad2e33b6c44dfa057e54928440d8b65401c0c15"
    end
    on_arm do
      url "https://github.com/isovalent/homebrew-isopolicy/raw/refs/heads/main/downloads/v0.16.0/pollux_Darwin_arm64.tar.gz"
      sha256 "b2e1a56fbf85beabf1f1dfcf4519809a3375bc9d9e180cbd0f6d9a1ebcaad6ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/isovalent/homebrew-isopolicy/raw/refs/heads/main/downloads/v0.16.0/pollux_Linux_amd64.tar.gz"
      sha256 "4bf68a83af9d63f9c6bc51918d04a5a896eed884597e39d554025d076bf78099"
    end
    on_arm do
      url "https://github.com/isovalent/homebrew-isopolicy/raw/refs/heads/main/downloads/v0.16.0/pollux_Linux_arm64.tar.gz"
      sha256 "0d72d0c84f7e5246fe6b0a5c963d582cc0d509a55797418fb99eff6d3a65b713"
    end
  end

  # No zap stanza required
end
